// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atnpzkqyyfyjkikmmali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bnB6a3F5eWZ5amtpa21tYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTg2MTksImV4cCI6MjA3MzQzNDYxOX0.0HKi04dcP7wdsQ9mVqUmXkrFs5wC4H8Wky3LO7-jEKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});